#!/usr/bin/env python

import requests
from urllib.request import urlopen as uReq
import bs4
from bs4 import BeautifulSoup as soup
import lxml
from time import sleep

filename ="customerData.csv"
f= open(filename,"w")

header="company,country,URL,first,last,title,number,Products\n"
f.write("")#
f.write(header)
number = 0
root = 'https://www.frozenb2b.com/DataBase/DatabaseMemberFiche.aspx?NoFiche=' + str(number)

for i in range(50000):
    root = "https://www.frozenb2b.com/DataBase/DatabaseMemberFiche.aspx?NoFiche=" + str(number)
    number += 1
    print(root)

    myurl = 'https://www.frozenb2b.com/DataBase/DatabaseMemberFiche.aspx?NoFiche=4686'

    # opening connection and grabbing a page
    uClient = uReq(root)
    page_html = uClient.read()
    uClient.close()

    # html parsing (conversion)
    page_soup = soup(page_html, "html.parser")
    #print(page_soup.body.div)
    try:
        comp_name = page_soup.find(id='cphContent_UCMemberFiche1_Company')
        comp_name = comp_name.get("value")
    except AttributeError:
        print("None")
        comp_name = " none"
        pass

    try:
        Country = page_soup.find(id='cphContent_UCMemberFiche1_Country_NoMember')
        Country = Country.text
    except AttributeError:
        print("None")
        Country= " none"
        pass
    try:
        URL = page_soup.find(id='cphContent_UCMemberFiche1_HLweb_NoMember')
        URL = URL.text
    except AttributeError:
        print("None")
        URL = " none"
        pass
    try:
        First_Name = page_soup.find(id='cphContent_UCMemberFiche1_FirstName_NoMember')
        First_Name = First_Name.text
    except AttributeError:
        print("None")
        First_Name = " none"
        pass


    try:

        Last_Name = page_soup.find(id='cphContent_UCMemberFiche1_Name_NoMember')
        Last_Name = Last_Name.text
    except AttributeError:
        print("None")
        Last_Name = " none"
        pass
    try:
        Title = page_soup.find(id='cphContent_UCMemberFiche1_Titre_NoMember')
        Title = Title.text
    except AttributeError:
        print("None")
        Title = " none"
        pass

    try:
        Number = page_soup.find(id='cphContent_UCMemberFiche1_TelProf1_NoMember')
        Number = Number.text
    except AttributeError:
        print("None")
        Number = " none"
        pass


    try:
        Frozen = page_soup.find(id='cphContent_UCMemberFiche1_productFrozen_NoMember')
        Frozen = Frozen.text
    except AttributeError:
        print("None")
        Frozen = " none"
        pass

    try:
        NonFrozen = page_soup.find(id='cphContent_UCMemberFiche1_productNonFrozen_NoMember')
        NonFrozen = NonFrozen.text
    except AttributeError:
        print("None")
        NonFrozen = " none"
        pass







    f.write(comp_name+ "," +Country + "," + URL+ "," + First_Name + "," + Last_Name + "," + Title + "," +Number  + "," + Frozen+ "," + NonFrozen + "\n")
    #print(Country.text)
    # print(URL.text)
    # print(First_Name.text)
    # print(Last_Name.text)
    # print(Title.text)
    # print(Number.text)
    # print(Frozen.text)
    # print(NonFrozen.text)
